language:
  - cpp
compiler:
  - g++
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - deb http://us.archive.ubuntu.com/ubuntu/ precise universe
  - deb-src http://us.archive.ubuntu.com/ubuntu/ precise universe
  - sudo apt-get update
  - sudo apt-get install gcc-4.8
  - sudo apt-get install libboost-dev libglew1.6-dev libsdl1.2-dev
script:
  - mkdir build 
  - cd build 
  - cmake ..
  - make -j4
  - make install
