language:
  - cpp
compiler:
  - g++
before_install:
  - sudo apt-get update
  - sudo apt-get install libboost-dev libyaml-dev libglew1.6-dev
script:
  - mkdir build 
  - cd build 
  - cmake ..
  - make -j4
  - make install
