language:
  - cpp
compiler:
  - g++
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - echo -e "deb http://ppa.launchpad.net/stephane.magnenat/precise/ubuntu presise main universe\ndeb-src http://ppa.launchpad.net/stephane.magnenat/precise/ubuntu precise main universe" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update || echo 'Screw it'
  - sudo apt-get upgrade -y || echo 'Screw it'
  - sudo apt-get build-dep yaml-cpp
  - sudo apt-get install curl
  - mkdir build
  - cd build
  - curl "https://yaml-cpp.googlecode.com/files/yaml-cpp-0.3.0.tar.gz" | tar xvfz -
  - cd yaml-cpp
  - mkdir build
  - cd build
  - cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
  - make -j4
  - sudo make install
  - cd ../..
  - rm -Rf yaml-cpp
  - sudo apt-get install gcc-4.7 libboost-dev libglew1.6-dev libsdl1.2-dev libgl1-mesa-dev
script:
  - mkdir build 
  - cd build 
  - cmake ..
  - make -j4
  - make install
