language:
  - cpp
compiler:
  - g++
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - echo -e "deb http://ppa.launchpad.net/stephane.magnenat/precise/ubuntu precise main universe\ndeb-src http://ppa.launchpad.net/stephane.magnenat/precise/ubuntu precise main universe" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update || echo 'Screw it'
  - sudo apt-get Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade -y || echo 'Screw it'
  - sudo apt-get install gcc-4.7 libboost-dev libglew1.6-dev libglfw-dev libgl1-mesa-dev
  - wget "http://downloads.sourceforge.net/project/glfw/glfw/3.0.3/glfw-3.0.3.zip?r=&use_mirror=optimate" -O glfw-3.0.3.zip && unzip glfw-3.0.3.zip && cd glfw-3.0.3 && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr .. && make -j4 && sudo make install
script:
  - mkdir build && cd build
  - cmake ..
  - make -j4
  - sudo make install
